<?php

namespace Database\Seeders;

use App\Models\Iphone;
use App\Models\Macbook;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TechSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
               $iphones = [
    ['name' => 'iPhone 16e 128GB Black',                'image' => 'images/iphone.jpg',                      'kategorija' => 'iPhone 16e',       'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Black',            'price' => 589.00,  'oldprice' => 729.00,  'arYra' => true],
    ['name' => 'iPhone 16e 128GB White',                'image' => 'images/iphone.jpg',                      'kategorija' => 'iPhone 16e',       'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'White',            'price' => 589.00,  'oldprice' => 729.00,  'arYra' => true],
    ['name' => 'iPhone 16e 256GB Black',                'image' => 'images/iphone.jpg',                      'kategorija' => 'iPhone 16e',       'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Black',            'price' => 649.00,  'oldprice' => 789.00,  'arYra' => true],
    ['name' => 'iPhone 16e 256GB White',                'image' => 'images/iphone.jpg',                      'kategorija' => 'iPhone 16e',       'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'White',            'price' => 649.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 15 128GB Black',                 'image' => 'images/iphone_15_black.jpg',             'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Black',            'price' => 689.00,  'oldprice' => 889.00,  'arYra' => true],
    ['name' => 'iPhone 15 128GB Blue',                  'image' => 'images/iphone_15_blue.jpg',              'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Blue',             'price' => 689.00,  'oldprice' => 889.00,  'arYra' => true],
    ['name' => 'iPhone 15 128GB Pink',                  'image' => 'images/iphone_15_pink.jpg',              'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Pink',             'price' => 689.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 15 256GB Black',                 'image' => 'images/iphone_15_black.jpg',             'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Black',            'price' => 789.00,  'oldprice' => 949.00,  'arYra' => true],
    ['name' => 'iPhone 15 256GB Yellow',                'image' => 'images/iphone.jpg',                      'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Yellow',           'price' => 789.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 15 512GB Black',                 'image' => 'images/iphone_15_black.jpg',             'kategorija' => 'iPhone 15',        'screenSize' => '6.1"', 'storage' => '512GB', 'color' => 'Black',            'price' => 949.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 15 Plus 128GB Black',            'image' => 'images/iphone_15_plus_black.jpg',        'kategorija' => 'iPhone 15 Plus',   'screenSize' => '6.7"', 'storage' => '128GB', 'color' => 'Black',            'price' => 799.00,  'oldprice' => 999.00,  'arYra' => true],
    ['name' => 'iPhone 15 Plus 256GB Blue',             'image' => 'images/iphone_15_plus_blue.jpg',         'kategorija' => 'iPhone 15 Plus',   'screenSize' => '6.7"', 'storage' => '256GB', 'color' => 'Blue',             'price' => 899.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 15 Plus 512GB Pink',             'image' => 'images/iphone_15_plus_pink.jpg',        'kategorija' => 'iPhone 15 Plus',   'screenSize' => '6.7"', 'storage' => '512GB', 'color' => 'Pink',             'price' => 1049.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 16 128GB Black',                 'image' => 'images/iphone_16_black.jpg',            'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Black',            'price' => 799.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 128GB White',                 'image' => 'images/iphone_16_white.jpg',            'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'White',            'price' => 799.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 128GB Teal',                  'image' => 'images/iphone_16_teal.jpg',             'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Teal',             'price' => 799.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 256GB Pink',                  'image' => 'images/iphone_16_pink.jpg',             'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Pink',             'price' => 899.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 256GB Ultramarine',           'image' => 'images/iphone_16_ultramarine.jpg',      'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Ultramarine',      'price' => 899.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 16 512GB Black',                 'image' => 'images/iphone_16_black.jpg',            'kategorija' => 'iPhone 16',        'screenSize' => '6.1"', 'storage' => '512GB', 'color' => 'Black',            'price' => 1099.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Plus 128GB Black',            'image' => 'images/iphone_16_plus_black.jpg',       'kategorija' => 'iPhone 16 Plus',   'screenSize' => '6.7"', 'storage' => '128GB', 'color' => 'Black',            'price' => 899.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Plus 256GB White',            'image' => 'images/iphone_16_plus_white.jpg',       'kategorija' => 'iPhone 16 Plus',   'screenSize' => '6.7"', 'storage' => '256GB', 'color' => 'White',            'price' => 999.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Plus 512GB Teal',             'image' => 'images/iphone_16_plus_teal.jpg',        'kategorija' => 'iPhone 16 Plus',   'screenSize' => '6.7"', 'storage' => '512GB', 'color' => 'Teal',             'price' => 1199.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 16 Pro 128GB Black Titanium',    'image' => 'images/iphone_16_pro_black.jpg',        'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '128GB', 'color' => 'Black Titanium',   'price' => 1099.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro 256GB White Titanium',    'image' => 'images/iphone_16_pro_white.jpg',        'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '256GB', 'color' => 'White Titanium',   'price' => 1199.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro 256GB Natural Titanium',  'image' => 'images/iphone_16_pro_natural.jpg',      'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '256GB', 'color' => 'Natural Titanium', 'price' => 1199.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro 512GB Black Titanium',    'image' => 'images/iphone_16_pro_black.jpg',        'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '512GB', 'color' => 'Black Titanium',   'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro 512GB Desert Titanium',   'image' => 'images/iphone_16_pro_desert.jpg',       'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '512GB', 'color' => 'Desert Titanium',  'price' => 1299.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 16 Pro 1TB Natural Titanium',    'image' => 'images/iphone_16_pro_natural.jpg',      'kategorija' => 'iPhone 16 Pro',    'screenSize' => '6.3"', 'storage' => '1TB',   'color' => 'Natural Titanium', 'price' => 1499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro Max 256GB Black Titanium','image' => 'images/iPhone_16_Pro_Max_black.jpg',    'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '256GB', 'color' => 'Black Titanium',   'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro Max 256GB White Titanium','image' => 'images/iPhone_16_Pro_Max_white.jpg',    'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '256GB', 'color' => 'White Titanium',   'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro Max 512GB Black Titanium','image' => 'images/iPhone_16_Pro_Max_black.jpg',    'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '512GB', 'color' => 'Black Titanium',   'price' => 1499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro Max 512GB Desert Titanium','image'=> 'images/iPhone_16_Pro_Max_desert.jpg',   'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '512GB', 'color' => 'Desert Titanium',  'price' => 1499.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 16 Pro Max 1TB Natural Titanium','image' => 'images/iPhone_16_Pro_Max_natural.jpg',  'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '1TB',   'color' => 'Natural Titanium', 'price' => 1699.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 16 Pro Max 1TB Desert Titanium', 'image' => 'images/iPhone_16_Pro_Max_desert.jpg',   'kategorija' => 'iPhone 16 Pro Max','screenSize' => '6.9"', 'storage' => '1TB',   'color' => 'Desert Titanium',  'price' => 1699.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 14 128GB Midnight',              'image' => 'images/iPhone_14_midnight.jpg',         'kategorija' => 'iPhone 14',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Midnight',         'price' => 549.00,  'oldprice' => 699.00,  'arYra' => true],
    ['name' => 'iPhone 14 128GB Starlight',             'image' => 'images/iPhone_14_starlight.jpg',        'kategorija' => 'iPhone 14',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Starlight',        'price' => 549.00,  'oldprice' => 699.00,  'arYra' => true],
    ['name' => 'iPhone 14 256GB Blue',                  'image' => 'images/iPhone_14_blue.jpg',             'kategorija' => 'iPhone 14',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Blue',             'price' => 649.00,  'oldprice' => 799.00,  'arYra' => true],
    ['name' => 'iPhone 14 256GB Red',                   'image' => 'images/iPhone_14_red.jpg',              'kategorija' => 'iPhone 14',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Red',              'price' => 649.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 14 Plus 128GB Midnight',         'image' => 'images/iPhone_14_midnight.jpg',         'kategorija' => 'iPhone 14 Plus',   'screenSize' => '6.7"', 'storage' => '128GB', 'color' => 'Midnight',         'price' => 649.00,  'oldprice' => 799.00,  'arYra' => true],
    ['name' => 'iPhone 14 Plus 256GB Starlight',        'image' => 'images/iPhone_14_starlight.jpg',        'kategorija' => 'iPhone 14 Plus',   'screenSize' => '6.7"', 'storage' => '256GB', 'color' => 'Starlight',        'price' => 749.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 13 128GB Midnight',              'image' => 'images/iPhone_13_midnight.jpg',         'kategorija' => 'iPhone 13',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Midnight',         'price' => 429.00,  'oldprice' => 599.00,  'arYra' => true],
    ['name' => 'iPhone 13 128GB Starlight',             'image' => 'images/iPhone_13_starlight.jpg',        'kategorija' => 'iPhone 13',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'Starlight',        'price' => 429.00,  'oldprice' => 599.00,  'arYra' => true],
    ['name' => 'iPhone 13 256GB Pink',                  'image' => 'images/iPhone_13_pink.jpg',             'kategorija' => 'iPhone 13',        'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Pink',             'price' => 529.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 13 mini 128GB Midnight',         'image' => 'images/iPhone_13_Mini_midnight.jpg',    'kategorija' => 'iPhone 13 mini',   'screenSize' => '5.4"', 'storage' => '128GB', 'color' => 'Midnight',         'price' => 379.00,  'oldprice' => 499.00,  'arYra' => true],
    ['name' => 'iPhone 13 mini 256GB Starlight',        'image' => 'images/iPhone_13_Mini_starlight.jpg',   'kategorija' => 'iPhone 13 mini',   'screenSize' => '5.4"', 'storage' => '256GB', 'color' => 'Starlight',        'price' => 479.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 13 Pro 256GB Graphite',          'image' => 'images/iPhone_13_Pro_graphite.jpg',     'kategorija' => 'iPhone 13 Pro',    'screenSize' => '6.1"', 'storage' => '256GB', 'color' => 'Graphite',         'price' => 699.00,  'oldprice' => 999.00,  'arYra' => true],
    ['name' => 'iPhone 13 Pro 512GB Sierra Blue',       'image' => 'images/iPhone_13_Pro_sierra_blue.jpg',  'kategorija' => 'iPhone 13 Pro',    'screenSize' => '6.1"', 'storage' => '512GB', 'color' => 'Sierra Blue',      'price' => 849.00,  'oldprice' => null,    'arYra' => false],
    ['name' => 'iPhone 13 Pro Max 256GB Graphite',      'image' => 'images/iPhone_13_Pro_Max_graphite.jpg', 'kategorija' => 'iPhone 13 Pro Max','screenSize' => '6.7"', 'storage' => '256GB', 'color' => 'Graphite',         'price' => 799.00,  'oldprice' => 1099.00, 'arYra' => true],
    ['name' => 'iPhone 13 Pro Max 512GB Gold',          'image' => 'images/iPhone_13_Pro_Max_gold.jpg',     'kategorija' => 'iPhone 13 Pro Max','screenSize' => '6.7"', 'storage' => '512GB', 'color' => 'Gold',             'price' => 949.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'iPhone 12 64GB Black',                  'image' => 'images/iPhone_12_black.jpg',            'kategorija' => 'iPhone 12',        'screenSize' => '6.1"', 'storage' => '64GB',  'color' => 'Black',            'price' => 299.00,  'oldprice' => 449.00,  'arYra' => true],
    ['name' => 'iPhone 12 128GB White',                 'image' => 'images/iPhone_12_white.jpg',            'kategorija' => 'iPhone 12',        'screenSize' => '6.1"', 'storage' => '128GB', 'color' => 'White',            'price' => 349.00,  'oldprice' => null,    'arYra' => false],
];

$macbooks = [
    ['name' => 'MacBook Air 13" M2 8GB 256GB Midnight',          'image' => 'images/macbook_air_13_midnight.jpg',    'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '8-core',  'ram' => '8GB',  'storage' => '256GB', 'color' => 'Midnight',        'price' => 999.00,  'oldprice' => 1199.00, 'arYra' => true],
    ['name' => 'MacBook Air 13" M2 8GB 256GB Starlight',         'image' => 'images/macbook_air_13_starlight.jpg',   'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '8-core',  'ram' => '8GB',  'storage' => '256GB', 'color' => 'Starlight',       'price' => 999.00,  'oldprice' => 1199.00, 'arYra' => true],
    ['name' => 'MacBook Air 13" M2 8GB 512GB Space Grey',        'image' => 'images/macbook_air_13_space_grey_blue.jpg','kategorija' => 'MacBook Air 13"','screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '512GB', 'color' => 'Space Grey',      'price' => 1199.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 13" M2 16GB 512GB Silver',           'image' => 'images/macbook_air_13_silver.jpg',      'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 13" M3 8GB 256GB Midnight',          'image' => 'images/macbook_air_13_midnight.jpg',    'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Midnight',        'price' => 1099.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 13" M3 8GB 256GB Starlight',         'image' => 'images/macbook_air_13_starlight.jpg',   'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Starlight',       'price' => 1099.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 13" M3 16GB 512GB Space Grey',       'image' => 'images/macbook_air_13_space_grey_blue.jpg','kategorija' => 'MacBook Air 13"','screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Space Grey',      'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 13" M3 24GB 1TB Silver',             'image' => 'images/macbook_air_13_silver.jpg',      'kategorija' => 'MacBook Air 13"',  'screenSize' => '13.6"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '24GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 1599.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'MacBook Air 15" M2 8GB 256GB Midnight',          'image' => 'images/macbook_air_15_midnight.jpg',    'kategorija' => 'MacBook Air 15"',  'screenSize' => '15.3"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Midnight',        'price' => 1199.00, 'oldprice' => 1399.00, 'arYra' => true],
    ['name' => 'MacBook Air 15" M2 8GB 512GB Silver',            'image' => 'images/macbook_air_15_silver.jpg',      'kategorija' => 'MacBook Air 15"',  'screenSize' => '15.3"', 'screenType' => 'Liquid Retina', 'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '512GB', 'color' => 'Silver',          'price' => 1399.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 15" M3 8GB 256GB Starlight',         'image' => 'images/macbook_air_15_starlight.jpg',   'kategorija' => 'MacBook Air 15"',  'screenSize' => '15.3"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Starlight',       'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 15" M3 16GB 512GB Space Grey',       'image' => 'images/macbook_air_15_space_grey_blue.jpg','kategorija' => 'MacBook Air 15"','screenSize' => '15.3"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Space Grey',      'price' => 1499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Air 15" M3 24GB 1TB Midnight',           'image' => 'images/macbook_air_15_midnight.jpg',    'kategorija' => 'MacBook Air 15"',  'screenSize' => '15.3"', 'screenType' => 'Liquid Retina', 'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '24GB', 'storage' => '1TB',   'color' => 'Midnight',        'price' => 1799.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'MacBook Pro 14" M3 8GB 512GB Space Black',       'image' => 'images/macbook_pro_14_space_black.jpg', 'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 8-core',  'gpu' => '10-core', 'ram' => '8GB',  'storage' => '512GB', 'color' => 'Space Black',     'price' => 1599.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M3 16GB 512GB Silver',           'image' => 'images/macbook_pro_14_silver.jpg',      'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 8-core',  'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1799.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M3 Pro 18GB 512GB Space Black',  'image' => 'images/macbook_pro_14_space_black.jpg', 'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Pro 11-core','gpu' => '14-core','ram' => '18GB', 'storage' => '512GB', 'color' => 'Space Black',     'price' => 1999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M3 Pro 18GB 1TB Silver',         'image' => 'images/macbook_pro_14_silver.jpg',      'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Pro 11-core','gpu' => '14-core','ram' => '18GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 2199.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M3 Max 36GB 1TB Space Black',    'image' => 'images/macbook_pro_14_space_black.jpg', 'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Max 14-core','gpu' => '30-core','ram' => '36GB', 'storage' => '1TB',   'color' => 'Space Black',     'price' => 2999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M3 Max 64GB 1TB Silver',         'image' => 'images/macbook_pro_14_silver.jpg',      'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Max 16-core','gpu' => '40-core','ram' => '64GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 3499.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'MacBook Pro 16" M3 Pro 18GB 512GB Space Black',  'image' => 'images/macbook_pro_16_space_black.jpg', 'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Pro 11-core','gpu' => '14-core','ram' => '18GB', 'storage' => '512GB', 'color' => 'Space Black',     'price' => 2499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M3 Pro 18GB 1TB Silver',         'image' => 'images/macbook_pro_16_silver.jpg',      'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Pro 11-core','gpu' => '14-core','ram' => '18GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 2699.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M3 Max 36GB 1TB Space Black',    'image' => 'images/macbook_pro_16_space_black.jpg', 'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Max 14-core','gpu' => '30-core','ram' => '36GB', 'storage' => '1TB',   'color' => 'Space Black',     'price' => 3499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M3 Max 64GB 1TB Silver',         'image' => 'images/macbook_pro_16_silver.jpg',      'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Max 16-core','gpu' => '40-core','ram' => '64GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 3999.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'MacBook Pro 16" M3 Max 64GB 2TB Space Black',    'image' => 'images/macbook_pro_16_space_black.jpg', 'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M3 Max 16-core','gpu' => '40-core','ram' => '64GB', 'storage' => '2TB',   'color' => 'Space Black',     'price' => 4499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M2 8GB 256GB',                          'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Silver',          'price' => 599.00,  'oldprice' => 699.00,  'arYra' => true],
    ['name' => 'Mac mini M2 8GB 512GB',                          'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '512GB', 'color' => 'Silver',          'price' => 799.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M2 Pro 16GB 512GB',                     'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Pro 10-core','gpu' => '16-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1099.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M4 16GB 256GB',                         'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 10-core',   'gpu' => '10-core', 'ram' => '16GB', 'storage' => '256GB', 'color' => 'Silver',          'price' => 599.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M4 16GB 512GB',                         'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 10-core',   'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 799.00,  'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M4 Pro 24GB 512GB',                     'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 Pro 12-core','gpu' => '20-core', 'ram' => '24GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac mini M4 Pro 64GB 1TB',                       'image' => 'images/mac_mini_silver.jpg',            'kategorija' => 'Mac mini',         'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 Pro 14-core','gpu' => '20-core', 'ram' => '64GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 1999.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iMac 24" M3 8GB 256GB Blue',                     'image' => 'images/imac_24_blue.jpg',               'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Blue',            'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M3 8GB 256GB Green',                    'image' => 'images/imac_24_green.jpg',              'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Green',           'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M3 8GB 256GB Pink',                     'image' => 'images/imac_24_pink.jpg',               'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '8GB',  'storage' => '256GB', 'color' => 'Pink',            'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M3 16GB 512GB Silver',                  'image' => 'images/imac_24_silver.jpg',             'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1699.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M3 24GB 1TB Yellow',                    'image' => 'images/mac.jpg',                        'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M3 8-core',    'gpu' => '10-core', 'ram' => '24GB', 'storage' => '1TB',   'color' => 'Yellow',          'price' => 1999.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'iMac 24" M4 16GB 256GB Blue',                    'image' => 'images/imac_24_blue.jpg',               'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M4 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '256GB', 'color' => 'Blue',            'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M4 16GB 256GB Green',                   'image' => 'images/imac_24_green.jpg',              'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M4 8-core',    'gpu' => '10-core', 'ram' => '16GB', 'storage' => '256GB', 'color' => 'Green',           'price' => 1299.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M4 24GB 512GB Pink',                    'image' => 'images/imac_24_pink.jpg',               'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M4 8-core',    'gpu' => '10-core', 'ram' => '24GB', 'storage' => '512GB', 'color' => 'Pink',            'price' => 1599.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'iMac 24" M4 32GB 1TB Silver',                    'image' => 'images/imac_24_silver.jpg',             'kategorija' => 'iMac',             'screenSize' => '24"',   'screenType' => 'Retina 4.5K',   'cpu' => 'M4 8-core',    'gpu' => '10-core', 'ram' => '32GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 1899.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'Mac Pro M2 Ultra 192GB 1TB',                     'image' => 'images/mac.jpg',                        'kategorija' => 'Mac Pro',          'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Ultra 24-core','gpu' => '60-core','ram' => '192GB','storage' => '1TB',  'color' => 'Silver',          'price' => 6999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac Pro M2 Ultra 192GB 2TB',                     'image' => 'images/mac.jpg',                        'kategorija' => 'Mac Pro',          'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Ultra 24-core','gpu' => '76-core','ram' => '192GB','storage' => '2TB',  'color' => 'Silver',          'price' => 7999.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'Mac Studio M2 Max 32GB 512GB',                   'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Max 12-core','gpu' => '30-core', 'ram' => '32GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac Studio M2 Max 32GB 1TB',                     'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Max 12-core','gpu' => '30-core', 'ram' => '32GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 2199.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac Studio M2 Ultra 64GB 1TB',                   'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M2 Ultra 24-core','gpu' => '60-core','ram' => '64GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 3999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac Studio M4 Max 36GB 512GB',                   'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 Max 14-core','gpu' => '32-core', 'ram' => '36GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'Mac Studio M4 Max 36GB 1TB',                     'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 Max 14-core','gpu' => '32-core', 'ram' => '36GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 2199.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'Mac Studio M4 Ultra 96GB 1TB',                   'image' => 'images/mac_studio_silver.jpg',          'kategorija' => 'Mac Studio',       'screenSize' => 'N/A',   'screenType' => 'N/A',           'cpu' => 'M4 Ultra 28-core','gpu' => '60-core','ram' => '96GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 3999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M4 16GB 512GB Silver',           'image' => 'images/macbook_pro_14_silver.jpg',      'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 10-core',  'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1599.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M4 16GB 512GB Space Black',      'image' => 'images/macbook_pro_14_space_black.jpg', 'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 10-core',  'gpu' => '10-core', 'ram' => '16GB', 'storage' => '512GB', 'color' => 'Space Black',     'price' => 1599.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M4 Pro 24GB 512GB Silver',       'image' => 'images/macbook_pro_14_silver.jpg',      'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Pro 12-core','gpu' => '20-core','ram' => '24GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 1999.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 14" M4 Pro 24GB 1TB Space Black',    'image' => 'images/macbook_pro_14_space_black.jpg', 'kategorija' => 'MacBook Pro 14"',  'screenSize' => '14.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Pro 12-core','gpu' => '20-core','ram' => '24GB', 'storage' => '1TB',   'color' => 'Space Black',     'price' => 2199.00, 'oldprice' => null,    'arYra' => false],
    ['name' => 'MacBook Pro 16" M4 Pro 24GB 512GB Silver',       'image' => 'images/macbook_pro_16_silver.jpg',      'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Pro 12-core','gpu' => '20-core','ram' => '24GB', 'storage' => '512GB', 'color' => 'Silver',          'price' => 2499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M4 Pro 24GB 1TB Space Black',    'image' => 'images/macbook_pro_16_space_black.jpg', 'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Pro 12-core','gpu' => '20-core','ram' => '24GB', 'storage' => '1TB',   'color' => 'Space Black',     'price' => 2699.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M4 Max 36GB 1TB Silver',         'image' => 'images/macbook_pro_16_silver.jpg',      'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Max 14-core','gpu' => '32-core','ram' => '36GB', 'storage' => '1TB',   'color' => 'Silver',          'price' => 3499.00, 'oldprice' => null,    'arYra' => true],
    ['name' => 'MacBook Pro 16" M4 Max 64GB 1TB Space Black',    'image' => 'images/macbook_pro_16_space_black.jpg', 'kategorija' => 'MacBook Pro 16"',  'screenSize' => '16.2"', 'screenType' => 'Liquid Retina XDR', 'cpu' => 'M4 Max 16-core','gpu' => '40-core','ram' => '64GB', 'storage' => '1TB',   'color' => 'Space Black',     'price' => 3999.00, 'oldprice' => null,    'arYra' => false],
];
                 foreach($iphones as $phone)
                {
                    Iphone::create([
                        'name'       => $phone['name'],
                        'image'      => $phone['image'],
                        'kategorija' => $phone['kategorija'],
                        'screenSize' => $phone['screenSize'],
                        'storage'    => $phone['storage'],
                        'color'      => $phone['color'],
                        'price'      => $phone['price'],
                        'oldprice'   => $phone['oldprice'],
                        'arYra'      => $phone['arYra'],


                    ]);
                }
           
                foreach($macbooks as $mac)
                {
                    Macbook::create([
                        'name'       => $mac['name'],
                        'image'      => $mac['image'],
                        'kategorija' => $mac['kategorija'],
                        'screenSize' => $mac['screenSize'],
                         'screenType' => $mac['screenType'],
                        'cpu' => $mac['cpu'],
                        'gpu' => $mac['gpu'],
                        'ram' => $mac['ram'],
                        'storage'    => $mac['storage'],
                        'color'      => $mac['color'],
                        'price'      => $mac['price'],
                        'oldprice'   => $mac['oldprice'],
                        'arYra'      => $mac['arYra'],


                    ]);
                }
    }
}
